config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/flat.rb
class Flat < ApplicationRecord
  validates :name, :address, :description, :price_per_night, :number_of_guests, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  def index
    @flat = Flat.all
  end

  def show
    @flat = Flat.find(params[:id])
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    if @flat.save
      redirect_to flats_path
    else
      render :new
    end
  end

  def edit
    @flat = Flat.find(params[:id])
  end

  def update
    @flat = Flat.find(params[:id])
    if @flat.update(flat_params)
      redirect_to flats_path
    else
      render :edit
    end
  end

  def destroy
    @flat = Flat.find(params[:id])
    @flat.destroy
    redirect_to flats_path
  end

  private

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/edit.html.erb
<div class="navbar navbar-dark bg-dark box-shadow">
  <div class="container d-flex justify-content-between">
    <a href="#" class="navbar-brand d-flex align-items-center">
      <strong> Apartment Rentals</strong>
        <%= link_to "Back to Main Menu", flats_path, class:"btn btn-primary my-2" %>

  </div>
  </div>

<main role="main">

  <section class="jumbotron text-center">
    <div class="container">
      <h1 class="jumbotron-heading">Edit your apartment</h1>
      <p class="lead text-muted">Please fill the form with the updated information</p>
      <p>
        <%= link_to "View All Apartments", flats_path, class:"btn btn-primary my-2" %>
      </p>
    </div>
  </section>


  <div class="album py-5 bg-light">
    <div class="container">
      <div class="row">
        <%= simple_form_for(@flat) do |f|  %>
          <%= f.input :name %>
          <%= f.input :address %>
          <%= f.input :description %>
          <%= f.input :price_per_night %>
          <%= f.input :number_of_guests %>
          <%= f.submit %>
        <% end %>
        <%= button_to "Delete Flat", @flat, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger mt-4' %>
      </div>
    </div>
  </div>

</main>

app/views/flats/index.html.erb
<div class="navbar navbar-dark bg-dark box-shadow">
  <div class="container d-flex justify-content-between">
    <a href="#" class="navbar-brand d-flex align-items-center">
      <strong> Apartment Rentals</strong>
    </a>
  </div>
</div>


<main role="main">

  <section class="jumbotron text-center">
    <div class="container">
      <h1 class="jumbotron-heading">Apartment List</h1>
      <p class="lead text-muted">Choose your apartment</p>
      <p>
        <%= link_to "Create a new post", new_flat_path, class:"btn btn-primary my-2" %>
      </p>
    </div>
  </section>

  <div class="album py-5 bg-light">
    <div class="container">
      <div class="row">

        <% @flat.each do |f| %>
        <div class="col-md-4">
          <div class="card mb-4 box-shadow">
            <img class="card-img-top" src="https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2" alt="Card image cap">
            <div class="card-body">
              <p class="card-text"><%= f.address  %></p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <%= link_to "View", flat_path(f), class:"btn btn-sm btn-outline-secondary"  %>
                  <%= link_to "Edit", edit_flat_path(f), class:"btn btn-sm btn-outline-secondary"  %>
                </div>
                <small class="text-muted">Price: $<%= f.price_per_night  %></small>
              </div>
            </div>
          </div>
        </div>
        <% end %>
      </div>
    </div>
  </div>

</main>

<footer class="text-muted">
  <div class="container">
    <p class="float-right">
      <a href="#">Back to top</a>
    </p>
    <p>Creaed by Arthur Andrade</p>

  </div>
</footer>

app/views/flats/new.html.erb
<div class="navbar navbar-dark bg-dark box-shadow">
  <div class="container d-flex justify-content-between">
    <a href="#" class="navbar-brand d-flex align-items-center">
      <strong> Apartment Rentals</strong>
        <%= link_to "Back to Main Menu", flats_path, class:"btn btn-primary my-2" %>

  </div>
  </div>

<main role="main">

  <section class="jumbotron text-center">
    <div class="container">
      <h1 class="jumbotron-heading">Create your apartment</h1>
      <p class="lead text-muted">Please fill the form</p>
      <p>
        <%= link_to "View All Apartments", flats_path, class:"btn btn-primary my-2" %>
      </p>
    </div>
  </section>


  <div class="album py-5 bg-light">
    <div class="container">
      <div class="row">
        <%= simple_form_for(@flat) do |f|  %>
          <%= f.input :name %>
          <%= f.input :address %>
          <%= f.input :description %>
          <%= f.input :price_per_night %>
          <%= f.input :number_of_guests %>
          <%= f.submit %>
        <% end %>
      </div>
    </div>
  </div>

</main>

app/views/flats/show.html.erb
<div class="navbar navbar-dark bg-dark box-shadow">
  <div class="container d-flex justify-content-between">
    <a href="#" class="navbar-brand d-flex align-items-center">
      <strong> Apartment Rentals</strong>
        <%= link_to "Back to Main Menu", flats_path, class:"btn btn-primary my-2" %>

  </div>
  </div>

  <main role="main">
    <section class="jumbotron text-center">
      <div class="container">
        <h1 class="display-4"><%= @flat.name  %></h1>
        <p class="lead">Address: <%= @flat.address %></p>
        <p class="lead">Price: $<%= @flat.price_per_night %></p>
        <a href="#" class="btn btn-primary">Book Now</a>
      </div>
    </section>
    <section class="card">
      <div class="card-body">
        <img class="card-img-top" src="https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2" alt="Card image cap">
        <p class="card-text"><%= @flat.description %></p>
      </div>
    </section>
  </main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnbV2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>